### PR TITLE
feat: Add ability to specify custom webhook parameters

### PR DESCRIPTION
**Pull request by janpieterz**
It would be great to add support for these custom webhook parameters, since this is still using the legacy integration.
If you'd prefer me to use the more explicit parameter mapping let me know, happy to refactor.

https://api.slack.com/legacy/custom-integrations/messaging/webhooks#legacy-customizations

### CODE REVIEW

**Comment by TheAppleFreak** [comment]
Sorry for the delay! Missed the email for this.

Everything looks good here. I'll merge that now.

**Comment by janpieterz** [comment]
Awesome, thank you @TheAppleFreak ! Any chance for a publish on NPM?

**Comment by TheAppleFreak** [comment]
v2.2.1 is now published! After publishing v2.2.0 I belatedly realized it didn't reintroduce the exact type of functionality present in v1.x, so I readded that code, updated the documentation, and published. Your code is still present and works as you expected, but you can also define those functions on the constructor once again and have those act as a default. 😄

**Comment by janpieterz** [comment]
Awesome, works great, thanks @TheAppleFreak

**Pull request merged**
